### ISSUE TITLE
Parenthesis Checker_using stack

### ISSUE THREAD

**Issue by Anjali-Chaudhary3** [shashank1623/Algorithms#51]
Problem Statement:
Given an expression string x. Examine whether the pairs and the orders of “{“,”}”,”(“,”)”,”[“,”]” are correct in exp.
For example, the function should return 'true' for exp = “[()]{}{[()()]()}” and 'false' for exp = “[(])”.

Approach:
Stack

**Comment by Anjali-Chaudhary3** [comment]
@shashank1623 please assign this issue to me.

**Comment by shashank1623** [comment]
yes you can work on it.

**Comment by adithya27082002** [comment]
pls assign me this

**Comment by Anjali-Chaudhary3** [comment]
@shashank1623 i have a much-optimized approach. Can I contribute?

**Comment by shashank1623** [comment]
> @shashank1623 i have a much-optimized approach. Can I contribute to the code?

i am assigning this work to you. now code and make a pr

**Comment by Anjali-Chaudhary3** [comment]
@shashank1623 i have added this under hacktoberfest 2022
