### ISSUE TITLE
Addition of Dynamic Programming in "Popular Coding Topics"

### ISSUE THREAD

**Issue by ashwinpra** [shashank1623/Algorithms#67]
I believe that Dynamic Programming should also be added in the "Popular Coding Topics" section, as it is quite handy in competitive programming. I would like to begin contributing to this section by adding the popular "knapsack" problem :)

**Comment by shashank1623** [comment]
Add the code and make pr. So that I can review and merge

**Comment by ashwinpra** [comment]
Done! :)

**Comment by shashank1623** [comment]
Good

**Comment by shashank1623** [comment]
Don't forget to star this repo. And follow my github account
