### ISSUE TITLE
Next Greater Element using stack

### ISSUE THREAD

**Issue by Anjali-Chaudhary3** [shashank1623/Algorithms#76]
Given an array arr[ ] of size N having elements, the task is to find the next greater element for each element of the array in order of their appearance in the array.Next greater element of an element in the array is the nearest element on the right which is greater than the current element.
Expected Time Complexity : O(N)
Expected Auxiliary Space : O(N)

**Comment by shashank1623** [comment]
code it. make a pr !. so that i can merge
